### PR TITLE
Some improvements in DCSDuraRepair.lua

### PR DESCRIPTION
**Pull request by Kakjens**
Moved some stuff outside of for loop, made DCS_Item_repairTotal() to return value which can be used inside other functions.

### CODE REVIEW

**Comment by Kakjens** [comment]
Somehow doesn't seem to work if pulling into merged.

**Comment by dejoblue** [comment]
Cool, cool. This one I want to review fully so it will take a while to get done. Keep em coming tho. :)

**Comment by Kakjens** [comment]
Not fully the changes I wanted to do with DCSDecimals.lua (e.g., didn't change the template for stats because we are modifying them with number of decimal places). At least no more two large areas of almost the same code.

**Comment by Kakjens** [comment]
Didn't optimize because didn't know whether you'll like the idea of some AI for determination of state.
Some obvious changes would be removal of the state in saved variables, renaming of the variable and not .making local versions of the state. Anything more (e.g., behavior after clicking the button) probably would require careful read.

**Review by dejoblue — APPROVED** [review]
I like it! Great idea counting the number of stats instead of checking the state.

**Review by dejoblue — APPROVED** [review]

**Comment by dejoblue** [comment]
We need to start making a branch for every major commit. 

So all of these commits were merged at once because they were all in the same branch. That means if everything was good except for the button changes then I wouldn't be able to merge the other changes until the button changes were ready.

I had the same issue with my own commits before and forgot to mention it to you.

Something logical like have the button changes be one branch and then have the durability/repair changes be another branch and then have the strength and stat tooltips be another branch.

Or even illogical, make as many branches as you want. I can delete them after they are merged.

You can keep and maintain your own branch and you can even make a branch off your own branch and we can even make branches off each other's branches, like I did here: https://github.com/dejoblue/DejaCharacterStats/pull/9

And as you can see do the pull request etc.

Anyway, it would make it easy to just click, click, click to merge the tooltip changes and then keep reviewing button changes.

By the way, see if you can review that pull request I linked. It is to revert your button changes. See if you can reject it, comment on it etc.

And to clarify, the changes all look good to me and I merged them. This is just a test as I want to make sure you have access to review my pulls etc.

I'll get this packaged and put up as a beta for players to test.

**Pull request merged**
