### PR TITLE
New curse localizations

### PR DESCRIPTION
**Pull request by dejoblue**
German and Russian And Fixes

### CODE REVIEW

**Comment by dejoblue** [comment]
German, Russian, French and Spanish, so far.

**Comment by dejoblue** [comment]
All languages with translations have been updated to new system. Made fixes and updated the About pop up. Let's get this out as a new beta. I know we will have more translations coming in as I told the Russian translator I would let him know when it went to beta and we also have a few new strings. I am sure we will have more to add even after release once more people see it and are interested in translating the little bits here and there.

Anyway, plan is for you to double check this pull and make sure I didn't do anything wrong, merge it, then upload as 730rc107. Then once we have 2000 download for a day or so we change it from beta to release. 730rc108 will have any new translations since 107 is the test for the system and we should only be adding new words and no new features. then we can branch off and start on Bonus XP and whatever else.

**Comment by Kakjens** [comment]
Yeah, no template and exporting directly from curseforge is the fastest. I feel some strings are still missing, and about 1/3 of them - not used.

**Comment by Kakjens** [comment]
I sense a problem with slash commands. Try "/dcstats reset" on Spanish locale.

**Comment by Kakjens** [comment]
Should all mouse-over tooltips be in third person describing what they do? Currently there are both ways.
L["Two Decimal Places"] = "Zwei Dezimalstellen" instead of "Zwei Nachkommastellen"
I really don't know the gender of all enhancement stats in German language but think that L["%s of %s increases %s by %.2f%%"] = "%s von %s erhöht die %s um %.2f%%." might be wrong. Maybe play safe with L["%s of %s increases %s by %.2f%%"] = "%s von %s erhöht %s um %.2f%%."?
There might be conflicts between dodge and parry. At least for me it is suspicious that L["Dodge Rating"] is similar to L["Parry"].
L["Off Hand"] should be L["/Off Hand"] 
L["weapon auto attack (white) DPS."] should begin with space.
This without logging in to WoW. Changing llocale to German for live tests.

**Comment by Kakjens** [comment]
Mouse - over tooltip for repair stat is in English.

**Comment by Kakjens** [comment]
Also, it seems there's a bug with layout (and visibility) of stats for new players.
And about unneeded localization strings - you can delete them individually after clicking pictograph of memo with pencil. After deletion, they should be still accessed by clicking a picture in the right corner of search box, and changing Status to "Deleted".

**Comment by dejoblue** [comment]
The whole point of translation is that we don't do it. If the wrong sex is used or wrong tense then that is not something we can really know. Having said that, when you find one you question, make your best guess as to what is correct. If you find an English translation just delete it.

Cool deal with the deleted strings. Let's go ahead and delete what is not used. 

> Also, it seems there's a bug with layout (and visibility) of stats for new players.

I have checked on my end and I do not encounter a problem. Is this a language specific problem? I have logged on to my level 110, 49, 1 and created a brand new Alliance and Horde character. Fresh German character, still no issue.

**Comment by Kakjens** [comment]
Created one semi-automated way for obtaining of used localization strings. Extinguishing unneeded on Curseforge.

**Comment by dejoblue** [comment]
Ah yeah, I have meant to remove the slash command localizations forever. That was a vestige of old, old mass localization I did with little thought, just trying to get it done, lol. 

I see "reset" wasn't deleted, descriptions says, "/dcstats reset slash command, In next pull won't be used." Go ahead and delete it if it isn't used. I didn't just in case you did something else with it or it is needed for something I am not thinking of.

I added a bunch of descriptions to some phrases that weren't obvious.

I think we can get this out as 730rc107 unless you had anything else. The release will be 730rc108. I want it out by Tuesday if not sooner.

Current plan is to put this in beta tomorrow after you get a chance to let me know if you have any major issues. Then I think we should release after 2000 beta downloads plus a day's time to make sure there are no major bugs. This will put us on track for release Before or by Tuesday. Translations will keep coming in for other languages so I expect us to have a patch or two to add those after beta and probably even after release. Right now we are polishing, adding little details, optimizing. It is more than good enough for a final beta. We can add any extra details for a small patch with more localization additions.

Let me know what you think.

**Comment by dejoblue** [comment]
I reviewed all translations that needed approved, exported, changed and uploaded all languages with the new list, i.e. removed all deleted phrases.

**Comment by Kakjens** [comment]
Let the tests for Russian language begin (it should be easier to see if something is wrong than in German)!

**Comment by dejoblue** [comment]
My guy says it looks beautiful! 

Nappsel:

> Done.
> 
> I translated and corrected all the phrases. Tested everything in the game, it looks great!
> There are two bugs, I showed them in the screenshot([Imgur Image](https://i.imgur.com/UNQQ150.jpg)). These are the phrases: Weapon DPS and Durability.
> 
> 
> In the same way, there is one phrase on the CurseForge with the status of Need Review - Agility. It is correct, it must be confirmed.

**Comment by Kakjens** [comment]
Seems like you didn't sync with my fixes for durability and weapon dps.

**Comment by dejoblue** [comment]
I did he is using the old version. You fixed it before he messaged me. I added you to our conversation on Curse.

**Pull request merged**
