### PR TITLE
Updated German Localization/Template

### PR DESCRIPTION
**Pull request by dejoblue**
Updated German Localization to be used as a template for all other
localizations.

### CODE REVIEW

**Comment by Kakjens** [comment]
Yes, the template needs updating. Wouldn't it be better to rename localization.enUS.lua into template.lua, update DejaCharacterStats.toc accordingly, and modify template.lua to reflect what in DCS is used?
Simply looking into code. Did you test it in-game before the change and after the change (some things don't look good - like, attributes should be deprecated with comment that we use Blizzard ones, or that there is stuff that you moved into deprecated but I feel that it's still used)?

**Comment by dejoblue** [comment]
I don't believe anything in deprecated is still used.

Good call on attributes.

I was looking into Curse's packaging system. Set up and API token and as we do commits here it can push those changes to a new release. Seems complicated for this project, but I know it is common to use.

Here is a couple of hits on it:

https://www.curseforge.com/docs/packaging

http://forums.riftgame.com/technical-discussions/addon-api-development/274536-curse-curseforge-now-supports-easy-localization-via-online-app.html

**Comment by Kakjens** [comment]
Will need to take better look for what is used and what is not.
I tried web-packaging for one of my addons, and the changelog looked... ugly. The second link seems to be for Rift.
I think that something already can be done via [curseforge](https://wow.curseforge.com/projects/dejacharacterstats/localization).

**Comment by dejoblue** [comment]
Yes, I know that we can do it via: https://wow.curseforge.com/projects/dejacharacterstats/localization

That is how we have been doing it, lol. :)

**Comment by dejoblue** [comment]
German and Russian have started. Gonna merge this and start adding what has been translated thus far.

**Pull request merged**
