### PR TITLE
Small optimization to ShowCharacterStats

### PR DESCRIPTION
**Pull request by Kakjens**
Small optimization to ShowCharacterStats

### CODE REVIEW

**Comment by dejoblue** [comment]
Oh cool, we can talk here about changes! Neato!

**Comment by Kakjens** [comment]
Indeed, it's possible to chat here as well.

**Comment by Kakjens** [comment]
I don't understand why in DCS_Item_DurabilityTop() function DCS_Mean_DurabilityCalc() gets called inside the for loop.

**Review by dejoblue — APPROVED** [review]
Looks good bla bla, testing!

**Pull request merged**
