### PR TITLE
Dcs 7 1 5 v1 0 0

### PR DESCRIPTION
**Pull request by dejoblue**
Stats display issue fix, but I have no idea why it works.

### CODE REVIEW

**Comment by Kakjens** [comment]
Verified - without `local statheight = StatFrame:GetHeight()` the position of frame after first opening, and consequent openings is different. Really strange - in normal programming language the compiler would see: variable calculated but not used. Does not seem to fix the "wonkiness" for stats display of Interface Options.

**Comment by dejoblue** [comment]
I wonder if statheight is a Blizzard variable in the Paperdollframe.lua. Setting the height again would do this. Hmm, maybe, but the scope is local. Weird.

**Comment by dejoblue** [comment]
> Does not seem to fix the "wonkiness" for stats display of Interface Options.

Yeah, I know, I didn't mean that it did, I was jsut explaining that without the line 198 the character stat frame acts very similar to the interface options, like it has not really been run or something.

**Comment by Kakjens** [comment]
Seem to be fixed it in other pull,

**Comment by dejoblue** [comment]
> Seem to be fixed it in other pull,

Seems so. Closing this.

**Pull request closed without merging**
