### PR TITLE
Maybe more intuitive version for checkboxes for hiding at zero 

### PR DESCRIPTION
**Pull request by Kakjens**
Probaby can be done without self:GetChecked() but will leave for some other time.

### CODE REVIEW

**Comment by dejoblue** [comment]
This gives an error. I think it is because Dcimals.lua loads after Layouts.lua so the default is not set when Layouts loads.

**Comment by dejoblue** [comment]
Interface\AddOns\DejaCharacterStats\DCSLayouts.lua:184: attempt to index field 'dejacharacterstatsHideAtZeroChecked' (a nil value)

**Comment by Kakjens** [comment]
Fixed. Those pesky upper and lower-case characters!

**Comment by dejoblue** [comment]
I don't like the yellow text, it breaks the aesthetic.

Don't use the word Blizzlike, that is a term used for private WoW servers, I don't want affiliation, even though I am not necessarily against them and play on Elysium. Use Blizzard, or Blizzard default or Default or something.

I also do not understand the difference between the two options. Can you explain that please?

**Comment by dejoblue** [comment]
I do like moving the Class Crest Background to the bottom of the top list.

**Comment by Kakjens** [comment]
I don't claim the coloring. I used the different coloring for separation of different clickable options. Something similar I intend to do for decimality of ilvl display.
I admit that I also played on private server - it was blizzlike, even (rates x4 or something). Maybe inadvertently used the term from memory. The wording can be changed.
There's mouse-over text for the options (at least, it should be). In case it's unclear/missing/other reason, there's some explanation. In DCS case, hiding at zero occurs if **displayed** value would be zero. For example, if Decimals is not checked and stat value is 0.1%, the stat will be hidden. Conversely, in Blizzard case, hiding at zero occurs if numerical value is **exactly** zero. So in previous example the stat would be displayed as 0%.
Testing of those options can be done by stripping nude a high-level character and dropping a campfire. It gives 4 versatility rating, which at sufficiently high level is converted to low versatility percentage (namely,  0.008% at level 110).
According to GnuclearGnome, there were cases when zeroed stats appear. For me it seemed a bug but now I consider that one of possible options.
Yes, moving of option for Class Crest Background  was intended (it's virtually impossible to do that otherwise). 
Later will fix the pulls.

**Comment by Kakjens** [comment]
Changed.

**Pull request merged**
