### PR TITLE
GetLocale() gets called just once per login

### PR DESCRIPTION
**Pull request by Kakjens**

### CODE REVIEW

**Comment by dejoblue** [comment]
Doesn't work. tested in German and Spanish. Most stats are using the Blizzard default localization so we didn't change those. Be sure to check the Interface Options panel that is most of what we translated,

**Comment by Kakjens** [comment]
Strange, will test and try to fix.

**Comment by Kakjens** [comment]
Seems to be fixed.

**Comment by dejoblue** [comment]
Looks good. Looks like we need to get a few more things translated too.

**Pull request merged**
