### PR TITLE
Rating localisations

### PR DESCRIPTION
**Pull request by Kakjens**
Several new strings for translators. Hopefully will make sense.

### CODE REVIEW

**Comment by dejoblue** [comment]
Concatenated the phrases so that all that needs to be translated is "Ratings".

Check it out and merge if it checks out on your tests, seems fine on my end with German and Russian.

**Comment by Kakjens** [comment]
The proposed German translations for ratings in most cases is one word. In Russian language the order is  wrong - it would be L["Rating"]..statname. That's why I think that previous version, when full phrase is translated, is better.

**Comment by dejoblue** [comment]
Yeah, I saw that with German, but it is doing that without our localization. Didn't get a chance to play with it. Looking at t now

**Comment by dejoblue** [comment]
Ahh, I see what you mean. I thought it was translating default from blizzard. I reverted my commit.

**Comment by dejoblue** [comment]
Why haven;t you added a versatility line similar to:

local ratingname = L["Versatility Rating"]

There are at least 5 instances of L["Versatility Rating"] between 679 and 683 where you could use ratingname isntead.

**Comment by Kakjens** [comment]
Thanks for noticing. Wrote without much thinking. Already was hesitating whether to have localization for stat names in lower case or to use capitalized Blizzard statname (e.g., L["haste"] or STAT_HASTE), so missed it.

**Comment by dejoblue** [comment]
NP, Thought I might have missed something like I did with the commit I did, heh.

**Pull request merged**
