### PR TITLE
Merge remote-tracking branch 'refs/remotes/origin/master' into Kakjen's_working_branch_1

### PR DESCRIPTION
**Pull request by Kakjens**
For some reason wants to pull despite no changes in files.
As you can see, played a bit with projects. Some management is good, and at-a-glance it's visible what someone else is up to.
In GitHub I don't see how to write a private message

### CODE REVIEW

**Comment by dejoblue** [comment]
If I am not mistaken, this is showing that I merged your pull into the master from your branch which was the origin. You may have to sync or update your branch to the master if you are having issues.

**Comment by dejoblue** [comment]
No, wait, looks like that is just where I updated the TOC file in DCS.

**Comment by dejoblue** [comment]
Yeah, I don't see messaging on here.

**Comment by dejoblue** [comment]
That is a fantastic idea!!!!

We could also remove the lock on the interface options menu because it is an entirely different button, DCS_InterfaceOptConfigButton, and when you close the menu it locks DCS.

I am heading to bed, but I'll get this reviewed tonight.

**Comment by dejoblue** [comment]
> For some reason wanted 2 commits
> 
> The pull has to be viewed as whole.

Just make a branch next time.

**Comment by Kakjens** [comment]
Since without the last commit there wouldn't be "Reset Stats" button when opening Interface Options (didn't check but that should be the case) decided to make a pull of three commits. This commit should be the last for this pull.
Leaving of "Lock DCS" button is intentional - with it the user can test how it would look on character stats info.

**Comment by Kakjens** [comment]
Found bug - If opening Character Info first and unlocking DCS, closing Character Info, and opening Interface Options, two unnamed buttons appear. Seems like some magic with anchors is required ><.

**Comment by dejoblue** [comment]
Gonna merge and put up on beta.

Also making a beta branch for us to work off of so we can push to it before merging to master directly. Be sure to create your own branch off of it.

**Review by dejoblue — APPROVED** [review]

**Pull request merged**
