### PR TITLE
Hack-solution

### PR DESCRIPTION
**Pull request by Kakjens**
Localization of movement speed. A real solution would be a our own function.

### CODE REVIEW

**Comment by dejoblue** [comment]
I like this solution. Making our own function would require more maintenance like if they change the function or subsequent calls etc later. Your thoughts?

**Comment by Kakjens** [comment]
Correct speed display when switching between flying and moving would require onupdate loop, which means our own function. Till it will be implemented, we'll have to suffer with slightly slower function,

**Comment by dejoblue** [comment]
Yeah it is a blizzard bug and part of why they abandoned it and other stats. Too much overhead for them to maintain it. There were comments in the alpha and beta that mentioned the issue with movement speed specifically.

This is perfect for localization tho, so Germans can at least see their movement speed lol

**Comment by dejoblue** [comment]
I don;t know if we should do an onupdate function tho because we do not show the display permanantly. i think most people will look at it while sitting still. Also people can simply hide and show the character stat frame to update it. If it is not a known issue I will add it.

**Comment by Kakjens** [comment]
Yes, it's not in the list of known issues, although I remember it (with the fix by reopening the character stats) being mentioned in youtube description of DCS..

**Pull request merged**
