### PR TITLE
Change of category name from Attack to Offense.

### PR DESCRIPTION
**Pull request by Kakjens**

### CODE REVIEW

**Comment by dejoblue** [comment]
I want to keep it consistent with most recent iteration in WoD. WoD changed Melee, Ranged and Spell into Attack as seen here: Wotlk/Cata/MoP on left, WoD on right: https://assets.tentonhammer.com/guides/attached_images/000/000/091/medium/wod-stats-before-and-after-no-text.jpg?1468380109

However, I like the idea of moving all of the stats assigned to Attack under Offense, but also adding four more headers that have nothing assigned and are at the bottom under Ratings and also not enabled when "All Stats" is clicked; Attack, Melee, Ranged, and Spell.

So default will be General, Attributes, Enhancements, and Offense. Then Ratings with its stats under it, then Attack, Melee, Ranged, and Spell with no attached stats.

Committing, even if we don;t add the extra headers, I like this idea better, it matches Blizzard's reassignment of all other secondary stats into a new "Enhancements" category.

**Comment by Kakjens** [comment]
Thanks for screenshots of how it looked. Helped to remember that there were several strange stats like Readiness etc.
The name "Offense" instead of "Attack" comes from comment in [Curse](https://mods.curse.com/addons/wow/dejacharacterstats?comment=708).
It's OK to add 4 invisible headers.
Did you miss Defense header? By the way, it somehow doesn't make much sense to have "Defense" header with a sole "Armor" visible for non-tanks. Making  "Defense" header to become invisible in that case is easy but can't see how to move "Armor" stat somewhere else. And additionally there are pesky shape-shifting druids - how it should look if non-guardian shape-shifts into bear. Maybe even guardian druid in non-bear doesn't want to know dodge%, and wants armor positioned somewhere else. Long time ago warriors had stances(the ones I remember were defensive and battle, plus one which has gone from memory). In this case as well it can be argued what stats in which case the user wants to see.
Maybe additional index - stance/shape-shift form is needed for database?

**Comment by dejoblue** [comment]
Stats automatically show and hide based on shapeshift form and spec. Druids, Warriors, Hunters and Warlocks used the stance system Warriors use, just named different. 

As far as Armor for non tanks we could make that class based in the table system: 

`if roles =  { "TANK" } then show else hide` <---- not actual code

**Comment by dejoblue** [comment]
Pull to address this: https://github.com/dejoblue/DejaCharacterStats/pull/124

**Pull request merged**
