### PR TITLE
Dejaitemlevelfix

### PR DESCRIPTION
**Pull request by dejoblue**
Blizzard's item level does not update with Artifacts on login. This is a quick fix for that.

### CODE REVIEW

**Comment by Kakjens** [comment]
So the fix is re-equipping shirt? What if character doesn't have it? What if bags are full?

**Comment by dejoblue** [comment]
This is part of the Artifact weapon not displaying properly. It is a Blizzard bug.

If the character doesn't have it then they are probably a low level character and do not have an artifact weapon.

If there is no shirt then nothing happens.

The only caveat is that if the player's computer loads slow then their shirt may not be equipped. That is why there is a 3 second delay. it only unequips on login. This is also why there is a call to equip the item when the paperdoll is shown. If they already have a shirt equipped nothing happens.

**Comment by Kakjens** [comment]
Leaving aside the necessity to save the shirt in so complex variable, there are other things to ask.
Seems like half of thread for [one bug](https://us.battle.net/forums/en/wow/topic/20753817475) don't have shirt equipped.
Wouldn't it be  better to detect the first opening of paperdoll for the re-equipping?

**Comment by dejoblue** [comment]
Here is a demo video I did. it is not public, https://www.youtube.com/watch?v=9CZqJyv8wTE

Hmm, maybe we could swap the trinkets on login and on paper doll open we put them back. 

I don't intend this to be permanent, I expect Blizzard to fix their bug, lol.

Maybe I should release it as a standalone addon only. 

my only concern is people complaining to us taht the ilvl is wrong, especially if the artifacts do not show the right ilvl. There is nothing we can do about it because the average ilvl is wrong to begin with.

**Comment by dejoblue** [comment]
Standalone addon uploaded to Discord in PMs. I am gonna play with the trinket swap idea. It would make it so people don't have to have a shirt in their bags.

Lemme know what you think. is it worth doing? Everything else is ready to go.

**Comment by Kakjens** [comment]
Since you'll be doing artifact ilvl calculation through relics, closing this pull.

**Pull request closed without merging**
