### PR TITLE
About dcs button and display

### PR DESCRIPTION
**Pull request by dejoblue**
Added an "About DCS" panel  display showing who makes DCS and thanking
them.

Also changed the text color of the version number in the bottom right
corner.

### CODE REVIEW

**Comment by Kakjens** [comment]
Didn't test in-game yet. Interesting addition but would prefer less attention to Interface options, at least for now. Ghost stats are scary! (will need to have a proper look what exactly happens when opening character info and interface options.
About the code:
Don't see the need for the first 4 lines in DCSAbout.lua.
There are two calls for DCSAboutDCSFrame:GetRight() and DCSAboutDCSFrame:GetLeft() instead of using one local variable which stores the difference.

**Comment by dejoblue** [comment]
You should test it in game. It only shows when you click the button by the game version in the interface Options Panel.

Ghost stats? What are you talking about?

The first 2 lines are needed for the button text localization. The other 2 are copy leftovers.

**Comment by dejoblue** [comment]
There we go I changed it now. Removed those 2 extraneous lines.

Check it out in game when you get a chance.

**Comment by Kakjens** [comment]
Search for "L[" indeed revealed that it gets used. Didn't notice when quickly run over the code, sorry.
Ghost stats sometimes appear appear after going to Interface options. I think we talked once about it. Not don't really remember how to reproduce but was connected with not fully opening DCS Interface Options. Testing now.

**Comment by dejoblue** [comment]
I do not do anything to the stats.

As far as the overlay persisting on login or once the interface frame is closed or changed, that is why I use the OnHide on line 31 - 33:

		DejaCharacterStatsPanel:SetScript("OnHide", function(self)
			DCSAboutDCSFrame:Hide()
		end)

Sorry I did not document. Ill add it here in a sec.

**Comment by dejoblue** [comment]
Documentation added. Hopefully makes sense now ;)

**Comment by Kakjens** [comment]
After reviewing the change of three lines merge.

**Pull request merged**
