### PR TITLE
Simplified chinese update

### PR DESCRIPTION
**Pull request by Kakjens**

### CODE REVIEW

**Comment by CrisReus** [comment]
hi, I'm C_Reus.
I have checked the release version and I think some of Chinese translations are not veritable and correct.
So，please updating the file which I uploaded yesterday.
You can find it on the comments.

**Comment by dejoblue** [comment]
Hi C_Reus ;)

Where did you upload the file? Can you provide a link?

We had some confusion with the Curse localization system so we had to manually check the translations.

Thanks again for your help.

Cheers!

**Comment by CrisReus** [comment]
local ADDON_NAME, namespace = ... 	--localization
local L = namespace.L 				--localization

--local LOCALE = GetLocale()

if namespace.locale == "zhCN" then
	-- The EU English game client also
	-- uses the US English locale code.

-- ###############################################################################################################################
-- ##	简体中文 (Simplified Chinese) translations provided by C_Reus(Azpilicuet@主宰之剑), alvisjiang, and y123ao6 on Curseforge.	##
-- ###############################################################################################################################

L["  /dcstats config: Opens the DejaCharacterStats addon config menu."] = "/dcstats config: 打开设置菜单。"
L["  /dcstats reset:  Resets DejaCharacterStats options to default."] = "/dcstats reset: 恢复默认设置。"
L["%s of %s increases %s by %.2f%%"] = "%s: %s 等于 %s: %.2f%%"
L["About DCS"] = "关于DCS" 
L["All Stats"] = "所有属性"
L["Attack"] = "攻击"
L["Average Durability"] = "平均耐久度"
L["Average equipped item durability percentage."] = "已装备的物品耐久度平均百分比"
L["Average Item Level:"] = "平均物品等级"
L["Avoidance Rating"] = "闪避值" 
L["Blizzard's Hide At Zero"] = "以游戏默认方式隐藏空值"
L["Character Stats:"] = "角色属性"
L["Class Colors"] = "职业颜色"
L["Class Crest Background"] = "职业特色背景"
L["Critical Strike Rating"] = "爆击值"
L["DCS's Hide At Zero"] = "以DCS方式隐藏空值"
L["Decimals"] = "小数点"
L["Defense"] = "防御"
L["DejaCharacterStats Slash commands (/dcstats):"] = "DejaCharacterStats 命令(/dcsstats)"
L["Displays \"Enhancements\" category stats to two decimal places."] = "显示\强化\栏的属性小数点后两位。"
L["Displays a durability bar next to each item."] = "在装备图标旁显示耐久条"
L["Displays average item durability on the character shirt slot and durability frames."] = "在角色界面衬衫栏与耐久度框架显示平均物品耐久度。"
L["Displays average item level to one decimal place."] = "显示平均装等小数点后一位"
L["Displays average item level to two decimal places."] = "显示平均装等小数点后两位"
L["Displays average item level with class colors."] = "以职业颜色显示平均物品等级"
L["Displays each equipped item's durability."] = "显示每件装备的耐久度"
L["Displays each equipped item's repair cost."] = "显示每件装备的维修费用"
L["Displays Equipped/Available item levels unless equal."] = "显示已装备/可用的物品等级除非相等。"
L["Displays the class crest background."] = "显示职业特色背景"
L["Displays the DCS scrollbar."] = "显示DejaCharacterStats滚动条"
L["Displays the Expand button for the character stats frame."] = "显示打开角色属性界面按钮。" 
L["Displays the item level of each equipped item."] = "显示已装备物品等级"
L["Dodge Rating"] = "躲闪值"
L["Durability"] = "耐久度"
L["Durability Bars"] = "耐久度条"
L["Equipped/Available"] = "已装备/可用"
L["Expand"] = "展开"
L["General"] = "综合"
L["General global cooldown refresh time."] = "公共冷却刷新时间。"
L["Global Cooldown"] = "公共冷却"
L["Haste Rating"] = "急速值"
L["Hide Character Stats"] = "隐藏人物属性"
L["Hides \"Enhancements\" stats if their displayed value would be zero. Checking \"Decimals\" changes the displayed value."] = "如果\强化\属性值为零则隐藏，开启\小数点\选项则显示"
L["Hides \"Enhancements\" stats only if their numerical value is exactly zero. For example, if stat value is 0.001%, then it would be displayed as 0%."] = "当\强化\属性值为零时隐藏，例：某属性值为0.001%，显示为0%"
L["Item Durability"] = "物品耐久度" 
L["Item Level"] = "物品等级"
L["Item Repair Cost"] = "物品修理费"
L["Item Slots:"] = "物品栏位"
L["Leech Rating"] = "吸血值"
L["Lock DCS"] = "锁定DCS"
L["Main Hand"] = "主手"
L["Mastery Rating"] = "精通值"
L["Miscellaneous:"] = "其他选项"
L["Movement Speed"] = "移动速度"
L["Off Hand"] = "副手"
L["Offense"] = "设置"
L["One Decimal Place"] = "小数点后一位"
L["Parry Rating"] = "招架值"
L["Ratings"] = "等级"
L["Relevant Stats"] = "相应属性"
L["Repair Total"] = "总修理费"
L["Requires Level "] = "需求等级"
L["Reset Stats"] = "重置属性"
L["Reset to Default"] = "恢复至默认配置"
L["Resets order of stats."] = "重置属性顺序"
L["Scrollbar"] = "滚动条"
L["Show all stats."] = "显示全部属性"
L["Show Character Stats"] = "显示角色属性"
L["Show only stats relevant to your class spec."] = "只显示你职业专精相关的属性"
L["Total equipped item repair cost before discounts."] = "折扣前的已装备物品修理费"
L["Two Decimal Places"] = "小数点后两位"
L["Unlock DCS"] = "解锁DCS"
L["Versatility Rating"] = "全能值"
L["weapon auto attack (white) DPS."] = "武器自动攻击(白字)每秒伤害。"
L["Weapon DPS"] = "武器伤害"

return end

I can't upload files in this project of github.
So, I issued the code in this comment.

**Comment by Kakjens** [comment]
Thanks. We will check the differences.
We are using [curseforge ](https://wow.curseforge.com/projects/dejacharacterstats/localization)localization system. The system might be buggy but it allows the localization translators to input their versions per-phrase so we could check them.

**Comment by CrisReus** [comment]
ok, I'll try it.

**Comment by Kakjens** [comment]
Hah, seem like github dislikes reversed "/" in comments, so pasting produces lua error during login. 
Nevertheless, soon (tm) will be a pull removing all \ in localization strings. Also, in several cases you simply removed a colon despite it possibly being warranted.

**Comment by CrisReus** [comment]
ok, I see. I will use other punctuation in localization.
You can change it to \“”\ .

XD

**Comment by Kakjens** [comment]
The changes seem verifiable with a help of, for example, google translator. Checked few and there indeed were improvements. Don't agree to removal of Chinese colons where English phrase had normal colon though. My biggest concern is about 
L["%s of %s increases %s by %.2f%%"] = "%s: %s 等于 %s: %.2f%%"
Somehow the structure of sentence feels wrong. How would you translate "Haste rating of 42 increases haste by 1%"?

**Comment by CrisReus** [comment]
Native Chinese is quite simple. Because we don't need much auxiliary word.
"=" also can be used, for example" haste rating 42 = haste 1%", Chinese translation is"急速值42等于1%急速"

**Comment by Kakjens** [comment]
Thanks, so word-by-word translation would be <haste rating><42>is<1%><haste>? It contradicts expected word order "<haste rating><42><haste><1%>" and explains some-what awkward second colon in the proposed phrase. How do you think, is a change template in the case of simplified Chinese into "<Rating name>: <integer> is <percent>%<stat>" warranted. Would it increase readability of description?
How does "显示'强化'栏位的属性小数点后两位。" for "Displays 'Enhancements' category stats to two decimal places." sound? "栏" google translates as column which feels wrong.
[Here](https://wow.curseforge.com/projects/dejacharacterstats/localization/languages/99/phrases#106793) is the next iteration of the simplified Chnese localization. Please tell what do you think.

**Pull request merged**
